name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler pages deploy ./out \
            --project-name=learn-semver \
            --commit-hash=${{ github.sha }} \
            --commit-message="${{ github.event.head_commit.message }}" \
            --branch=${{ github.ref_name }}
            
      - name: Comment deployment URL
        if: github.event_name == 'push'
        run: |
          echo "🚀 Deployed to Cloudflare Pages"
          echo "Preview: https://${{ github.sha }}.learn-semver.pages.dev"
          echo "Production: https://semver.agenticinsights.com"